<?php

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * implements hook_help().
 */

function configform_example_help($route_name, RouteMatchInterface $route_match) {
  switch($route_name) {
    case 'configform_example_form':
      return t('This is help text for the config form example ');
      break;

    //case 'help.page.page_example':
    //  return t("this is help text creating in the page example's implementation of hook_help().");
  }
  return;
}
