configform_example_form:
  path: '/examples/configform_example/simple'
  defaults:
    _form: '\Drupal\configform_example\Form\ConfigFormExampleConfigForm'
    _title: 'Configuration Example Form'
  requirements:
    _permission: 'access simple page'

#    _access: 'TRUE'


